spring.application.name=Cinema
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema-db
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
